### ISSUE TITLE
GPLv3 license is too restrictive to use in real project

### ISSUE THREAD

**Issue by apla** [tladesignz/jsPduDecoder#2]
Hi, I really like your project because it is (probably) only one which really works. Unfortunately, FSF [clearly states that code which is using library should be with the same license](https://www.gnu.org/licenses/lgpl-java.html). So, if I plan to use part of your javascript in my private nodejs project, I will violate the license. Can you release actual decoding part with permissive license, such as MIT?

**Comment by tladesignz** [comment]
No worries, I already did this:

> This program is free software; you can redistribute it and/or modify it under the terms of either: 
> the GNU General Public License as published by the Free Software Foundation; or the Artistic 
> License.
>
> See http://dev.perl.org/licenses/ for more information.

As written in [README.md](https://github.com/tladesignz/jsPduDecoder/blob/master/README.md).

Since this project was originally done in a Perl context, that's what I choose for licensing, too.

So you can use the software under the terms of the [Artistic License](http://dev.perl.org/licenses/artistic.html) which should give you what you need: [tldrlegal.com](https://tldrlegal.com/license/artistic-license-2.0-(artistic))

However, I recognize, that I didn't correctly reflect that in the `package.json` file. A fix for that is on its way.

Anyway. If you have any changes to this software, which may be relevant to others, I urge you to share this with everybody. Send me pull requests!
